### ISSUE TITLE
Vega-lite 2

### ISSUE THREAD

**Issue by hadim** [vegas-viz/Vegas#109]
Hello,

We are investigating the use of your library into the [Scijava Jupyter Kernel](https://github.com/scijava/scijava-jupyter-kernel/issues/73) and so I was wondering if you are planning to upgrade Vegas to the upcoming Vega-lite 2?

Thank you

**Comment by rgbkrk** [comment]
Once released, certainly so. We'll want to target `'application/vnd.vega.v2+json'` and `'application/vnd.vegalite.v2+json'` as in https://github.com/altair-viz/altair/pull/216/files#diff-17a20b3d62216a8cb5fc9108399964ecR20

**Comment by hadim** [comment]
Awesome.

But do you mean Vega 3? I thought Vega-lite 2 was based on Vega 3.

**Comment by rgbkrk** [comment]
Ah yeah. Today we'll support the `vega.v2` and `vegalite.v1` mimetypes in Jupyter frontends, and after their next release we'll support the new versions.

**Comment by hadim** [comment]
By the way, you might be aware but in case you don't know, Vega and Vega-lite renderers will be shipped by default in the next JLab release: https://github.com/altair-viz/jupyter_vega/issues/35 (and in the Notebook in a near future).
