### ISSUE TITLE
How to define logarithmic scale?

### ISSUE THREAD

**Issue by erbenpeter** [vegas-viz/Vegas#110]
I tried to set the scale of one of my axes to logarithmic like this:
```scala
val plot = Vegas("Country population & area").
  withDataFrame(df).
  encodeX("population", Quantitative).
  encodeY("area", Quantitative, scale=Scale(`type`=ScaleType.Log)).
  mark(Point)
```
but I got `error: not found: value type` exception.

What is the proper syntax for doing this?

**Comment by brentondwalker** [comment]
I was able to get logarithmic scale by doing something like this:
`encodeX("x", Quant, scale=Scale(Some(vegas.ScaleType.Log)))`

**Comment by erbenpeter** [comment]
> I was able to get logarithmic scale by doing something like this:
Thanks @brentondwalker , worked for me.
