### ISSUE TITLE
How to specify the size of the plot in standalone mode

### ISSUE THREAD

**Issue by wuciawe** [vegas-viz/Vegas#123]
Is it possible to configure the witdh and height of the plot ?

**Comment by thimmy687** [comment]
Hello @wuciawe ,

yes it is

".configCell(width = 500, height = 500)"

see this folder for different examples 

https://github.com/vegas-viz/Vegas/tree/master/core/src/test/scala/vegas/fixtures

**Comment by wuciawe** [comment]
@thimmy687 thanks. I'm busy these days, not having time to try this out. I will close this issue for now.
