### ISSUE TITLE
[proposal] Remove dependency on Argus

### ISSUE THREAD

**Issue by oshikiri** [vegas-viz/Vegas#158]
vega-lite recently released [v2.6.0](https://github.com/vega/vega-lite/releases/tag/v2.6.0) and [v3.0.0-rc6](https://github.com/vega/vega-lite/releases/tag/v3.0.0-rc6). However, Vegas currently depends on vega-lite v1.2.0 because the Argus's `anyOf` issue (https://github.com/vegas-viz/Vegas/issues/83) blocks upgrading vega-lite to v1.2.1 (and the issue seems to be hard to resolve: https://github.com/aishfenton/Argus/issues/13).

If we remove dependency on Argus and then maintain [Spec.scala](https://github.com/vegas-viz/Vegas/blob/master/core/src/main/scala/vegas/spec/Spec.scala) manually, can we avoid the above issue and upgrade vega-lite to newer than v1.2.1? 

I will try this if it is ok.

**Comment by dankolesnikov** [comment]
@oshikiri This will potentially help in #156 
Is Spec.scala the only file that depends on Argus package? Are there other classes that use argus?

**Comment by oshikiri** [comment]
@dankolesnikov Thanks 😄 

>Is Spec.scala the only file that depends on Argus package?

`core/src/test/scala/vegas/JsonMatchers.scala` also uses Argus but it seems not to be critical.
https://github.com/vegas-viz/Vegas/search?q=argus&unscoped_q=argus

**Comment by dankolesnikov** [comment]
@oshikiri 
`Spec.scala` seems to be a very large file to maintain. It seems logical to break down into multiple classes for easier maintenance.

Is `argus` library semi-abandoned?

**Comment by oshikiri** [comment]
@dankolesnikov 
+1 but I'm not sure if I can remove Argus.

I am trying to remove Argus and upgrade vega-lite at a *sandbox* branch, but now some tests are failing.
https://github.com/oshikiri/Vegas/compare/workspace-mkvegamodel...oshikiri:remove-argus

In the sandbox branch, there is still a dependency to argus at [JsonMatchers.scala](https://github.com/vegas-viz/Vegas/blob/d1941b6680f660e45fa95b94551b93e01ecf5d32/core/src/test/scala/vegas/JsonMatchers.scala). Do you have any ideas for this? (replacing `argus.json.JsonDiff` with another one, like for example  [scalatest-json](https://github.com/stephennancekivell/scalatest-json))

**Comment by aishfenton** [comment]
I'm going to have a go at resolving the issue in Argus.

**Comment by oshikiri** [comment]
I came to think that automatically generation of Spec.scala is required because `vega-lite-schema.json` grows very fast; 2260 lines ([v1.2.0](https://github.com/vega/vega-lite/blob/v1.2.0/vega-lite-schema.json)) → 8932 lines ([v2.6.0](https://github.com/vega/vega-lite/blob/v2.6.0/build/vega-lite-schema.json)) → 10123 lines ([v3.0.0-rc6](https://github.com/vega/vega-lite/blob/v3.0.0-rc6/build/vega-lite-schema.json)).

@aishfenton Could you please provide more details of the plan? (Is it related to https://github.com/aishfenton/Argus/issues/13?)

**Comment by aishfenton** [comment]
Yes,
Basically working now on updating Argus to support newer versions of JSON
Schema, and in general be more maintainable (move from Macros to Scalameta
mostly). Then we should be able to just generate a vega-lite schema for v3
again, and hopefully update it more frequently from then on.

**Comment by oshikiri** [comment]
@aishfenton Thanks. I think your plan is better.

P.S. Could you please check https://github.com/vegas-viz/Vegas/issues/138#issuecomment-429370077?
