### ISSUE TITLE
Make notebook import easier

### ISSUE THREAD

**Issue by aishfenton** [vegas-viz/Vegas#77]
Currently notebook import requires this somewhat ugly line:

`implicit val displayer: String => Unit = (s) => println(s"%html $s")`

Explore if we can hide it. 

Problem is with Jupyter. You need access to it's "display" variable, so you'd need to pass that into some kind of init method. But then the displayer itself is an implicit, so needs to be in local scope. Hmmmm... To be explored.

**Comment by rogermenezes** [comment]
Fixed with https://github.com/vegas-viz/Vegas/commit/8ae4b223575f71819a056e69a7bb7122b0d41611

The notebooks also have been updated to remove the implicit change:
https://github.com/vegas-viz/Vegas/commit/5540ce349ff938252fc56a69190411989fc1ca5e
