### ISSUE TITLE
sbt mkVegaModel fails

### ISSUE THREAD

**Issue by DarinJ** [vegas-viz/Vegas#93]
[error] /Users/.../Vegas/spec/src/main/scala/vegas/spec/Spec.scala:5: exception during macro expansion: 
[error] java.lang.Exception: Input stream is null
[error] 	at argus.schema.Schema$.fromInputStream(Schema.scala:15)
[error] 	at argus.schema.Schema$.fromResource(Schema.scala:25)
[error] 	at argus.macros.SchemaMacros.extractParams(FromSchema.scala:83)
[error] 	at argus.macros.SchemaMacros.fromSchemaMacroImpl(FromSchema.scala:137)
[error] @fromSchemaResource("/vega-lite-schema.json", name="Vega", outPath=Some("/Users/.../Vegas/spec/target/scala-2.11/Spec.scala"))
[error]  ^
[error] one error found
[error] (vegaLiteSpec/compile:compileIncremental) Compilation failed
[error] Total time: 6 s, completed Jan 23, 2017 3:07:54 PM

Is this still the way to rebuild to spec.scala file?  I did change the path to a path on my system vs /Users/afenton/...

**Comment by oshikiri** [comment]
@aishfenton Although I rewrote the `outPath`, I met the same error.

Could you provide the procedure for regenerating Spec.scala?

https://github.com/vegas-viz/Vegas/blob/v0.3.11/CONTRIB.md#dev-and-debugging-tips

**Comment by oshikiri** [comment]
I thought that the following annotation (to [Spec.scala](https://github.com/vegas-viz/Vegas/blob/v0.3.11/spec/src/main/scala/vegas/spec/Spec.scala)) should work, but it still fails with the same error: `java.lang.Exception: Input stream is null`.

```scala
// it still raises "Input stream is null" exception
@fromSchemaResource(
  path = "/spec/src/main/resources/vega-lite-schema.json",
  name = "Vega",
  outPath = Some("spec/target/scala-2.11/Spec.scala")
)
```

https://github.com/aishfenton/Argus/issues/2 seems to be the cause of this exception.

The following quick workaround has worked in my environment.

```scala
// it usually works, but infrequently fails...
@fromSchemaURL(
  url = "https://vega.github.io/schema/vega-lite/v1.2.0.json",
  name = "Vega",
  outPath = Some("spec/target/scala-2.11/Spec.scala")
)
```
