### ISSUE TITLE
please update circe to latest version !

### ISSUE THREAD

**Issue by izhangzhihao** [vegas-viz/Vegas#95]
The old version of `circe` contains a depreated dependency -- a very old version of `cat`,
many of the latest libraries rely on updated `cat`, so when using these libraries at the same time will lead to conflict.

```
"io.circe" %% "circe-core" % "0.7.0"
```

**Comment by dbtsai** [comment]
Sorry for late reply. Can you submit a PR for this? I could help to review it. Thanks.

**Comment by rogermenezes** [comment]
Updated circe to 0.7.0, and released Vegas 0.3.9
